services:
  - type: web
    name: medcast
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: MEDCAST
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:zHHNs3mMJwHxriJgmZK3w6GKphvfSaBdcAyQVtMLNK4=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: APP_URL
        value: https://medcast.onrender.com
      - key: SESSION_SECURE_COOKIE
        value: "true"
